image: registry.gitlab.com/bytesized/appbox-plex/build-image:latest
stages:
  - build

Build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375
  services:
  - docker:dind
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build --pull -t bytesized/appbox-plex:latest -f Dockerfile .
    - docker push bytesized/appbox-plex:latest
    - rm -rf ~/.docker
  retry: 1
